spring.application.name=SpringDataRest
spring.h2.console.enabled=true
spring.datasource.platform=h2
spring.datasource.url=jdbc:h2:mem:kajal
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
server.port=9494

